server:
  port: 8888

prop:
  upload-folder: D:/parkingFile/
  imgPathPatterns: http://localhost:8888/img/  #img访问映射路径

spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  datasource:   #指定使用的数据库驱动程序类名
    driverClassName: com.mysql.cj.jdbc.Driver
    #指定了数据库的地址、端口和数据库名称。这里使用的是本地的 MySQL 服务器，连接到名为 shared_park2 的数据库。
    #URL中的其他参数 useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai 用于设置数据库连接的编码和时区。
    url:  jdbc:mysql://localhost:3306/shared_park2?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root #数据库的登陆用户名
    password: 123456  #数据库的登陆密码

  #spring:
  #  datasource:
  #   url: jdbc:mysql://localhost:3306/shared_park2?serverTimezone=UTC&allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false
  #    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
  #    url: jdbc:sqlserver://localhost:1433;DatabaseName=sharedPark
  #    username: sa
  #    password: 123

#  flyway:
#    baseline-on-migrate: true
#    locations: classpath:/db/migration
#    check-location: true
#    enabled: true

#打印sql语句
#mybatis-plus:
#  configuration:
#  log-impl:org.apache.ibatis.logging.stdout.StdOutImpl
#  mybatis-plus.mapper-locations=classpath:mapper/*.xml
#  # 实体扫描，多个package用逗号或者分号分隔
#  mybatis-plus.type-aliases-package=com.example.mybatisplus.entity
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl



